version: '3'
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react-app-container
    image: reactjs-guvi:latest
    ports:
      - "808080808080808080:80"
