name: build and deploy 

on:
  push:
    branches:
      - dev  

jobs:
  build:
    run-on: ubuntu-latest 

    steps: 
      name: checkout repository 
      uses: action/checkout@v3

      name: build docker image
      run: bash build.sh 

      name: deploy appliction 
      run: bash docker.sh 

      name: docker hub login 
      uses: docker/login-action@v3
      with: 
        username: ${{ secretes.DOCKERHUB_USERNAME }}
        password: ${{ secretes.DOCKERHUB_PASSWORD }}

      name: push to docker hub 
      uses: docker/push-action@v3
      with:
        push: true 
        tags: rehan008/github-action:latest
