name: docker build and deploy

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      # - name: Generate SSH key
      #   run: |
      #     mkdir -p ~/.ssh
      #     ssh-keygen -t rsa -b 4096 -f ~/.ssh/id_rsa -N ""
      #     # Print the public key to be added to the server
      #     cat ~/.ssh/id_rsa.pub

      - name: Build Docker image
        run: sh build.sh

      - name: Deploy application
        run: sh deploy.sh

      - name: Docker Hub login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Extract Matadata (tags, labels)for docker 
        id: Meta
        uses: docker/metadata-action@v3
        with:
          images: rehan008/github-action
      
      - name: Push to Docker Hub
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels}}
     
      # - name: Generate SSH key
      #   run: |
      #     ssh ubuntu@ec2-52-66-242-35.ap-south-1.compute.amazonaws.com
      #     ls
      # - name: Deploy to AWS EC2
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.REMOTE_HOST }}
      #     username: ${{ secrets.REMOTE_USER }}
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: SSH into EC2 instance and deploy application
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} ec2-52-66-242-35.ap-south-1.compute.amazonaws.com
